# static position definitions
# start position
start: {x: 0.0, y: 0.0, z: 0.0, q1: 0.0, q2: 0.0, q3: 0.0, q4: 1.0}

# base position
base: {x: 1.52, y: -0.5, z: 0.0, q1: 0.0, q2: 0.0, q3: 0.0, q4: 1.0}

# goals
# labor tmech
goal_0: {x: -1.64, y: 2.55, z: 0.0, q1: 0.0, q2: 0.0, q3: -0.2, q4: 0.9796, folder: '/kurt'}
# labor robin
goal_1: {x: 5.6, y: 1.96, z: 0.0, q1: 0.0, q2: 0.0, q3: 0.0, q4: 1.0, folder: '/werkstatt'}
# labor desreg
goal_2: {x: 13.3, y: 1.76, z: 0.0, q1: 0.0, q2: 0.0, q3: 0.0, q4: 0.0, folder: '/diplomanden'}
# labor fluid
goal_3: {x: 23.05, y: 1.6, z: 0.0, q1: 0.0, q2: 0.0, q3: -0.707, q4: 0.707, folder: '/bib'}
